name: calculator_widget
description: Calculator widget for Converter NOW

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Needed for calculator computation
  decimal: ^3.0.2
  #Needed for the state management
  flutter_riverpod: ^2.6.1
  #Needed for app translation
  translations:
    path: ../translations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
